# Generated by Django 2.2.1 on 2020-04-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=10, unique=True)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('buy_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.BuyUser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_purchased', to='inventory.Item')),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machine.VendingMachine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('curr_count', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.Item')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machine.VendingMachine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
